### ISSUE TITLE
Question regarding refining workflow

### ISSUE THREAD

**Issue by backyardbiomech** [DeepLabCut/napari-DLCLabelingAlpha#6]
I'm pretty sure I used this before for refining labels, but now I can't get it to work properly:

If I drag a folder containing a machine labels file, it shows the originally labeled, not extracted points, but all images (loads collected data by default, which is expected). 
If I delete that key points layer and drag in the machine labels, it shows all the frames and only the extracted labels. 
If I refine those and save, it doesn't include the original labels in the output (good thing I backed up that collected data file). So how can I use it to refine labels properly?

Also, in the instructions, I would add a reminder before selecting save layer as as (or ctrl-S) to make sure the key points layer is selected. If the user clicked on the images layer first, does save as, then closes the window, any labeling work during that session will be lost.

**Comment by MMathisLab** [comment]
part 2, done!  https://github.com/DeepLabCut/napari-DeepLabCut/commit/671343b085a7c6badb653a16afe00abf580fe367

will look into 1, cc @jeylau
